### ISSUE TITLE
Support _properties key in tm2 projects

### ISSUE THREAD

**Issue by gravitystorm** [kosmtik/kosmtik#177]
tm2 projects can contain a top-level `_properties` attribute, which contains a list of layer-specific properties to pass on to mapnik. For example:

```
_properties: 
  building: 
    "group-by": level
```

This eventually ends up as an attribute of the layer in the mapnik stylesheet, e.g.

```
<Layer name="building"
  group-by="level"
  srs="+proj=merc +a[...]
```

Carto doesn't support this directly, instead it's up to the software loading the tm2 project to apply the attributes to the layers before handing over to carto. For example, here is the code in [mapbox studio classic](https://github.com/mapbox/mapbox-studio-classic/blob/a1d0953ab2b76a00e3125771d9ab180116a05064/lib/style.js#L254-L263)

**Comment by nebulon42** [comment]
Instead of implementing this at every software wouldn't it be better to include it into Carto?

**Comment by gravitystorm** [comment]
@nebulon42 I've no idea why it wasn't included in carto originally, maybe there was a reason. @yhahn originally implemented the _properties key in https://github.com/mapbox/mapbox-studio-classic/commit/95a59f7c4d2668cf3c699331b2a6df387c3267f4

**Comment by nebulon42** [comment]
I'm not too familiar with TM2 projects, but I suspect that `_properties` was necessary as you normally only reference the layers in a vector tile source. Carto already supports something similar for layers you define in the MML: https://github.com/mapbox/carto/blob/af92b76f94b10887c23479a14f39bb688e1b06d5/test/rendering/layer_properties.mml#L10.

**Comment by gravitystorm** [comment]
Ah, that makes sense. I usually end up defining the layers in my tm2 projects anyway, so I'd forgotten that you can omit them and fall back to the order defined in the source (necessitating the _properties workaround).

**Comment by pnorman** [comment]
Any progress on this, or at least a way to set if you are defining all the layers you're using?

**Comment by nebulon42** [comment]
No, but I welcome PRs for Carto.

**Comment by nebulon42** [comment]
@pnorman When you write

>  at least a way to set if you are defining all the layers you're using

Why can't you just use the properties object for each layer if you define them anyway? I linked an example in https://github.com/kosmtik/kosmtik/issues/177#issuecomment-250546262. Or what I'm understanding wrong?

**Comment by pnorman** [comment]
> Why can't you just use the properties object for each layer if you define them anyway? I linked an example in #177 (comment). Or what I'm understanding wrong?

I define a list of layers that are used, I don't have tilemill-style layer definitions.

My style YAML file is

```yml
_prefs:
  mapid: ''
  saveCenter: false
_properties:
  transport:
    "group-by": layer
scale: 1
metatile: 1
interactivity_layer: ''
name: Brighmed
description: OSM for Wikipedia with Meddo tiles
bounds: &world
  - -180
  - -85.05112877980659
  - 180
  - 85.05112877980659
center:
  - 0
  - 0
  - 4
format: "png"
minzoom: 0
maxzoom: 19
srs: "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over"
source: "tmsource:///home/user/path/to/meddo"
styles:
  - style.mss
  - water.mss
  # other files
layers:
  - landcover
  - waterway
  # other layers
```
