### ISSUE TITLE
mapbox vector tile support

### ISSUE THREAD

**Issue by jbrwn** [kosmtik/kosmtik#82]
Does kosmtik support mapbox vector tile workflows?  I pointed kosmtik at mapbox studio source project (tm2source) and everything seemed to work as expected. For example:

```node index.js serve ../tilemill/test_source.tm2source/data.yml```

However, when i tried to use a mapbox studio sytle project (tm2) a few blank tiles were rendered and then i got a hard error.

```node index.js serve ../tilemill/test2.tm2/project.yml```

```
Joels-MacBook-Pro:kosmtik joelbrown$ node index.js serve ../tilemill/test2.tm2/project.yml
[Core] No usable config file found in /Users/joelbrown/.config/kosmtik.yml
[Core] Loading plugin from ../plugins/base-exporters/index.js
[Core] Loading plugin from ../plugins/hash/index.js
[Core] Loading plugin from ../plugins/local-config/index.js
[Core] Loading plugin from ../plugins/datasource-loader/index.js
[Core] Loading project from ../tilemill/test2.tm2/project.yml
[Core] PreviewServer started, you can browse http://127.0.0.1:6789
[Local Config] Unable to load local config from /Users/joelbrown/tilemill/test2.tm2/localconfig.js
[Error: File not found: /Users/joelbrown/tilemill/test2.tm2/localconfig.js]
[datasource loader] Loading source from /Users/joelbrown/tilemill/test_source.tm2source
[Core] Loading project from /Users/joelbrown/tilemill/test_source.tm2source/data.yml
[Core] Generating Mapnik XML…
[Core] Using mapnik version 3.0.0
[Core] Loading map…
[Core] Map ready
[Core] Loading map…
[Core] Map ready
[Local Config] Unable to load local config from /Users/joelbrown/tilemill/test_source.tm2source/localconfig.js
[Error: File not found: /Users/joelbrown/tilemill/test_source.tm2source/localconfig.js]
[Core] Generating Mapnik XML…
[Core] Using mapnik version 3.0.0
[Core] Loading map…
[Core] Map ready
[Core] Loading map…
[Core] Map ready
[httpserver] / 302
[httpserver] /test2.tm2 302
[httpserver] /test2.tm2/ 200
[httpserver] /node_modules/leaflet/dist/leaflet-src.js 200
[httpserver] /node_modules/leaflet-formbuilder/Leaflet.FormBuilder.js 200
[httpserver] /config/ 200
[httpserver] /test2.tm2/config/ 200
[httpserver] /src/front/Core.js 200
[httpserver] /src/front/Autocomplete.js 200
[httpserver] /node_modules/leaflet/dist/leaflet.css 200
[httpserver] /src/front/Sidebar.css 200
[httpserver] /src/front/Toolbar.css 200
[httpserver] /src/front/Core.css 200
[httpserver] /src/front/DataInspector.js 200
[httpserver] /src/front/MetatilesBounds.js 200
[httpserver] /src/front/Sidebar.js 200
[httpserver] /src/front/Toolbar.js 200
[httpserver] /src/front/FormBuilder.js 200
[httpserver] /src/front/Settings.js 200
[httpserver] /src/front/Command.js 200
[httpserver] /src/front/Map.js 200
[httpserver] /src/plugins/base-exporters/front/export.js 200
[httpserver] /node_modules/leaflet-hash/leaflet-hash.js 200
[httpserver] /hash.js 200
[httpserver] /src/front/header_logo.svg 200
[httpserver] /src/front/fonts/FiraSans-Light.woff 200
[httpserver] /src/front/fonts/DejaVuSans-webfont.woff 200
[httpserver] /test_source.tm2source/tile/0/0/0.pbf 200
[httpserver] /test2.tm2/tile/0/0/0.png?t=1438974731391 200
[httpserver] /test_source.tm2source/tile/1/0/0.pbf 200
[httpserver] /test_source.tm2source/tile/1/1/0.pbf 200
[httpserver] /test2.tm2/tile/1/0/0.png?t=1438974731391 200
[httpserver] /test_source.tm2source/tile/1/0/1.pbf 200
[httpserver] /test2.tm2/tile/1/1/0.png?t=1438974731391 200
[httpserver] /test2.tm2/tile/1/0/1.png?t=1438974731391 200
[httpserver] /test_source.tm2source/tile/1/1/1.pbf 200
[httpserver] /test2.tm2/tile/1/1/1.png?t=1438974731391 200
[httpserver] /test_source.tm2source/tile/2/1/1.pbf 200
[httpserver] /test_source.tm2source/tile/2/2/1.pbf 200
[httpserver] /test2.tm2/tile/2/1/1.png?t=1438974731391 200
[httpserver] /test2.tm2/tile/2/2/1.png?t=1438974731391 200
[httpserver] /test_source.tm2source/tile/2/2/0.pbf 200
[httpserver] /test_source.tm2source/tile/2/2/2.pbf 200
[httpserver] /test2.tm2/tile/2/2/2.png?t=1438974731391 200
[httpserver] /test_source.tm2source/tile/2/1/0.pbf 200
cannot accept empty buffer as protobuf
Trace
    at ProjectServer.raise (/Users/joelbrown/kosmtik/src/back/ProjectServer.js:239:13)
    at /Users/joelbrown/kosmtik/src/back/ProjectServer.js:73:34
    at /Users/joelbrown/kosmtik/src/back/VectorBasedTile.js:61:18
    at parse (/Users/joelbrown/kosmtik/src/back/VectorBasedTile.js:24:17)
    at Request.onResponse [as _callback] (/Users/joelbrown/kosmtik/src/back/VectorBasedTile.js:41:17)
    at Request.self.callback (/Users/joelbrown/kosmtik/node_modules/request/request.js:198:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/Users/joelbrown/kosmtik/node_modules/request/request.js:1057:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/Users/joelbrown/kosmtik/node_modules/request/request.js:1003:12)
Unable to parse vector tile data for uri http://127.0.0.1:6789/test_source.tm2source/tile/2/1/0.pbf
[httpserver] /test2.tm2/tile/2/1/0.png?t=1438974731391 500
[httpserver] /test2.tm2/tile/2/2/0.png?t=1438974731391 200
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write after end
    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:413:15)
    at /Users/joelbrown/kosmtik/src/back/ProjectServer.js:77:21
```

Any idea what could be going on? 
My use case for kosmtik is that i have some non mapbox hosted mapnik vector tile services (.pbf) and i would like to use kosmtik to style that data.  i was using existing mapbox studio projects to test this out vector tile support and this is where i got stuck.

**Comment by yohanboniface** [comment]
> Any idea what could be going on? 

I think the issue is that Mapbox services needs authentication, and Kosmtik doesn't handle that. I'd like to have a plugin to do that in the future, but not using it myself it's not at top of my todo list.

If you use any open vector tile, it works (I use it myself, with both custom services or [Mapzen vector-datasource stack](https://github.com/mapzen/vector-datasource)

**Comment by jbrwn** [comment]
@yohanboniface Thanks for the response.

There are no mapbox services used in my example above.  I should have made it more clear.  The tm2 project references a local tm2source project. Here is the yml file:

```
_prefs: 
  saveCenter: true
_properties: 
  bridge: 
    "group-by": layer
attribution: "<a href='https://www.mapbox.com/about/maps/' target='_blank'>&copy; Mapbox &copy; OpenStreetMap</a> <a class='mapbox-improve-map' href='https://www.mapbox.com/map-feedback/' target='_blank'>Improve this map</a>"
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - 12.6563
  - 29.5352
  - 0
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 5
minzoom: 0
name: ''
source: "tmsource:///Users/joelbrown/tilemill/test_source.tm2source"
styles: 
  - style.mss
template: ''
```

>If you use any open vector tile, it works (I use it myself, with both custom services or Mapzen vector-datasource stack).

This is what i am actually trying to do.  Would you be able to provide an example of how you are doing this.  e.g., what does your yml file look like?

**Comment by yohanboniface** [comment]
Ah ok, sorry.
Well, I usually use remote vector tile sources (like in [thank you map example](https://github.com/yohanboniface/thank-you-map)).
But I do have an example of tm2 project that works, and here is the yml:
```yml
_prefs: 
  baselayer: ''
  print: false
  saveCenter: true
_properties: {}
attribution: Map data © OpenStreetMap contributors
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -85.8252
  - 32.7965
  - 6
description: ''
format: "png8:m=h:c=128"
interactivity_layer: ''
layers:
  - country_fill
  - playas
  - urban_areas
  - water
  - ice
  - railroads
  - roads
  - geographic_lines
  - admin_1_lines
  - admin_0_lines
  - country_labels
  - state_labels
  - land_ocean_labels
  - places
  - ports
maxzoom: 22
minzoom: 0
name: Natural Earth
source: "tmsource:///home/ybon/Code/maps/natural-earth-tm2/natural-earth.tm2source"
styles: 
  - style.mss
  - labels.mss
template: ''
metatile: 1
```
Try referencing by hand the layers you want to use?
